/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JPanel;
import Vista.panelChatServidor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;



/**
 *
 * @author D4K4R
 */
public class Vista extends javax.swing.JFrame implements ActionListener  {

    
    panelChatServidor miPanelChat = new panelChatServidor();
    FrameChatCliente chatCliente = new FrameChatCliente();

    
    public Vista() {
        initComponents();
        
        
        this.setLocationRelativeTo(null);
        
        
        
        
        
        
        btnChat.addActionListener(this);
        btnInicio.addActionListener(this);

        
    }

    /**
     
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        btnInicio = new javax.swing.JButton();
        btnChat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        jToolBar2.setRollover(true);

        btnInicio.setText("Inicio");
        btnInicio.setFocusable(false);
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnInicio);

        btnChat.setText("chat");
        btnChat.setFocusable(false);
        btnChat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnChat);

        getContentPane().add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
        
        
        
        
    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChat;
    private javax.swing.JButton btnInicio;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        Object evt = ae.getSource();
        if (evt.equals(btnChat)){
            
            panelPrincipal.add(this.miPanelChat);
            panelPrincipal.validate();
            this.chatCliente.setVisible(true);

        
        }
    }
}
